package products;

import java.util.ArrayList;

import static ru.aplana.tools.Common.generateRqUID;

/**
 * Generating xml for auto product
 * 
 * @author Maksim Stepanov
 *
 */
public class Auto {

	private String xml = null;
	
	private ArrayList<String> data = new ArrayList<String>(2);
	
	public Auto(int subproduct, String operation ) {

		String RQUID = generateRqUID();
		
		int dayWait = 5+ (int) (Math.random() * ((10 - 5) +1)); // [5,10]
		
		this.data.add(RQUID);
		
		this.data.add(operation);
		
		
		this.xml = new String("<tns:productInfoMessageRetail xsi:schemaLocation=\"tns productInfoMessageRetail.xsd\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:tns=\"tns\">"+
				"<tns:AUTO>"+
				"<tns:UID>"+RQUID+"</tns:UID>"+
				"<tns:PARAMS_BUSINESS>"+
					"<tns:SEGMENT_BUSINESS_1>"+
						"<tns:PRODUCT_TYPE>2</tns:PRODUCT_TYPE>"+
						"<tns:UNIQUEID_PRODUCT>10</tns:UNIQUEID_PRODUCT>"+
						"<tns:PRODUCT_NAME>Автокредит - заявка принята у дилера</tns:PRODUCT_NAME>"+
						"<tns:UNIQUEID_SUBPRODUCT>"+subproduct+"</tns:UNIQUEID_SUBPRODUCT>"+
						"<tns:SUBPRODUCT_NAME>Продукт_АВТО-2-10 (ЛА)</tns:SUBPRODUCT_NAME>"+
						"<tns:CURRENCY>RUB</tns:CURRENCY>"+
						"<tns:INCLUDED_BRANCH>18</tns:INCLUDED_BRANCH>"+
						"<tns:EXCLUDED_BRANCH/>"+
						"<tns:ID_USLOVIY_KRED>27</tns:ID_USLOVIY_KRED>"+
						"<tns:KOD_NORM_DOC_PO_KRED_FIZLIC>320</tns:KOD_NORM_DOC_PO_KRED_FIZLIC>"+
						"<tns:TYP_PROC_STAVKI_OSN_DOLG>2</tns:TYP_PROC_STAVKI_OSN_DOLG>"+
						"<tns:TYP_PROC_STAVKI_PO_NEUSTOYKE>9</tns:TYP_PROC_STAVKI_PO_NEUSTOYKE>"+
						"<tns:TYPP_ROC_STAVKI_NEUST_PO_PROC>9</tns:TYPP_ROC_STAVKI_NEUST_PO_PROC>"+
						"<tns:PENALTY>0.5</tns:PENALTY>"+
						"<tns:NEUSTOYKA_PO_PROCENTAM>0.6</tns:NEUSTOYKA_PO_PROCENTAM>"+
						"<tns:GUARANTORS>0</tns:GUARANTORS>"+
						"<tns:CO_APPLICANT>2</tns:CO_APPLICANT>"+
						"<tns:KOD_TYP_FORM_DOG>012241156/1</tns:KOD_TYP_FORM_DOG>"+
						"<tns:federal_company>Y</tns:federal_company>"+
						"<tns:COMMISSION>0.04</tns:COMMISSION>"+
						"<tns:MIN_COMISS_OBSL_SSUD>0.02</tns:MIN_COMISS_OBSL_SSUD>"+
						"<tns:MAX_COMISS_OBSL_SSUD>0.06</tns:MAX_COMISS_OBSL_SSUD>"+
						"<tns:CURRENCY_COMISS>RUB</tns:CURRENCY_COMISS>"+
					"</tns:SEGMENT_BUSINESS_1>"+
					"<tns:SEGMENT_BUSINESS_2>"+
						"<tns:NAIMENOVANIE_VIDA_KREDITA>Автокредит</tns:NAIMENOVANIE_VIDA_KREDITA>"+
						"<tns:ANNUITY_FLAG>1</tns:ANNUITY_FLAG>"+
						"<tns:DIFF_FLAG>0</tns:DIFF_FLAG>"+
					"</tns:SEGMENT_BUSINESS_2>"+
					"<tns:SEGMENT_BUSINESS_5>"+
						"<tns:NAIMEN_NORM_DOC_PO_KRED_FIZ_LIC>Регламент 1736-2-р</tns:NAIMEN_NORM_DOC_PO_KRED_FIZ_LIC>"+
					"</tns:SEGMENT_BUSINESS_5>"+
					"<tns:SEGMENT_BUSINESS_7>"+
						"<tns:KOD_TYP_FORM_DOG_CBR>012241157/1</tns:KOD_TYP_FORM_DOG_CBR>"+
					"</tns:SEGMENT_BUSINESS_7>"+
					"<tns:SEGMENT_BUSINESS_8>"+
						"<tns:KOD_VIDA_OBESP>15</tns:KOD_VIDA_OBESP>"+
						"<tns:KOD_TIP_FORM_DOG_OBESP>012241159/1</tns:KOD_TIP_FORM_DOG_OBESP>"+
					"</tns:SEGMENT_BUSINESS_8>"+
					"<tns:SEGMENT_BUSINESS_21>"+
						"<tns:Type_of_delinquency_charge_rate_on_wrong_insurance>2</tns:Type_of_delinquency_charge_rate_on_wrong_insurance>"+
						"<tns:Delinquency_charge_rate_on_wrong_insurance>0.1</tns:Delinquency_charge_rate_on_wrong_insurance>"+
						"<tns:Min_delinquency_charge_rate_on_wrong_insurance>0.01</tns:Min_delinquency_charge_rate_on_wrong_insurance>"+
						"<tns:Max_delinquency_charge_rate_on_wrong_insurance>0.2</tns:Max_delinquency_charge_rate_on_wrong_insurance>"+
						"<tns:Subsidy_fee_rate>5.5</tns:Subsidy_fee_rate>"+
						"<tns:KOD_SOVM_PROGRAMMY_AUTO>555</tns:KOD_SOVM_PROGRAMMY_AUTO>"+
					"</tns:SEGMENT_BUSINESS_21>"+
					"<tns:SEGMENT_BUSINESS_22>"+
						"<tns:CS_Insurance>0</tns:CS_Insurance>"+
					//Lazutin: fix expected tags 
						"<tns:Insurance_Discount0>0</tns:Insurance_Discount0>"+
						"<tns:Insurance_Discount1>0</tns:Insurance_Discount1>"+
						"<tns:Insurance_Discount2>0</tns:Insurance_Discount2>"+
					"</tns:SEGMENT_BUSINESS_22>"+
				"</tns:PARAMS_BUSINESS>"+
				"<tns:PARAMS_BUSINESS_TB TB_CODE=\"0\">"+
					"<tns:SEGMENT_BUSINESS_1_TB>"+
						"<tns:MIN_AMOUNT>20000.0</tns:MIN_AMOUNT>"+
						"<tns:MAX_AMOUNT>40000.0</tns:MAX_AMOUNT>"+
					"</tns:SEGMENT_BUSINESS_1_TB>"+
					"<tns:SEGMENT_BUSINESS_2_TB>"+
						"<tns:SUPLEMENTARY_CARD>1</tns:SUPLEMENTARY_CARD>"+
						"<tns:IssuanceCreditCard_MA>Y</tns:IssuanceCreditCard_MA>"+
						"<tns:Params_IssuanceCreditCard_MA>1</tns:Params_IssuanceCreditCard_MA>"+
						"<tns:IssuanceCreditCard_CBR>Y</tns:IssuanceCreditCard_CBR>"+
						"<tns:Params_IssuanceCreditCard_CBR>1</tns:Params_IssuanceCreditCard_CBR>"+
						"<tns:IssuanceOfaNewDepositAccount>Y</tns:IssuanceOfaNewDepositAccount>"+
						"<tns:IssuanceOfanExistingDepositAccount>Y</tns:IssuanceOfanExistingDepositAccount>"+
						"<tns:IssuanceOfaNewDebitCard>Y</tns:IssuanceOfaNewDebitCard>"+
						"<tns:IssuanceOfanExistingDebitCard>Y</tns:IssuanceOfanExistingDebitCard>"+
						"<tns:IssuanceOfaNewCurrentAccount>Y</tns:IssuanceOfaNewCurrentAccount>"+
						"<tns:IssuanceOfanExistingCurrentAccount>Y</tns:IssuanceOfanExistingCurrentAccount>"+
					"</tns:SEGMENT_BUSINESS_2_TB>"+
					"<tns:SEGMENT_BUSINESS_9_TB>"+
						"<tns:SALARY_PRODUCT>0</tns:SALARY_PRODUCT>"+
					"</tns:SEGMENT_BUSINESS_9_TB>"+
					"<tns:SEGMENT_BUSINESS_21_TB>"+
						"<tns:AUTO_NEW_GRA_MAX_LIM>40000</tns:AUTO_NEW_GRA_MAX_LIM>"+
						"<tns:AUTO_NEW_GRA1_MAX_LIM>40000</tns:AUTO_NEW_GRA1_MAX_LIM>"+
						"<tns:AUTO_NEW_GRB_MAX_LIM>40000</tns:AUTO_NEW_GRB_MAX_LIM>"+
						"<tns:AUTO_NEW_GRC_MAX_LIM>40000</tns:AUTO_NEW_GRC_MAX_LIM>"+
						"<tns:AUTO_NEW_GRC1_MAX_LIM>40000</tns:AUTO_NEW_GRC1_MAX_LIM>"+
						"<tns:AUTO_NEW_GRD_MAX_LIM>40000</tns:AUTO_NEW_GRD_MAX_LIM>"+
						"<tns:AUTO_NEW_GRE_MAX_LIM>40000</tns:AUTO_NEW_GRE_MAX_LIM>"+
						"<tns:AUTO_USED_GRA_MAX_LIM>40000</tns:AUTO_USED_GRA_MAX_LIM>"+
						"<tns:AUTO_USED_GRA1_MAX_LIM>40000</tns:AUTO_USED_GRA1_MAX_LIM>"+
						"<tns:AUTO_USED_GRB_MAX_LIM>40000</tns:AUTO_USED_GRB_MAX_LIM>"+
						"<tns:AUTO_USED_GRC_MAX_LIM>40000</tns:AUTO_USED_GRC_MAX_LIM>"+
						"<tns:AUTO_USED_GRC1_MAX_LIM>40000</tns:AUTO_USED_GRC1_MAX_LIM>"+
						"<tns:AUTO_USED_GRD_MAX_LIM>40000</tns:AUTO_USED_GRD_MAX_LIM>"+
						"<tns:AUTO_USED_GRE_MAX_LIM>40000</tns:AUTO_USED_GRE_MAX_LIM>"+
					"</tns:SEGMENT_BUSINESS_21_TB>"+
				"</tns:PARAMS_BUSINESS_TB>"+
				"<tns:PARAMS_RISK>"+
					"<tns:SEGMENT_RISK_1>"+
						"<tns:DopProductKodForSM>88</tns:DopProductKodForSM>"+
						"<tns:MAX_REVISION_NUMBER>7</tns:MAX_REVISION_NUMBER>"+
						"<tns:APPROVAL_VALIDITY>180</tns:APPROVAL_VALIDITY>"+
						"<tns:DECLINE_SEARCH>60</tns:DECLINE_SEARCH>"+
						"<tns:UNDWRT2_LIMIT>2000000</tns:UNDWRT2_LIMIT>"+
						"<tns:UNDWRT3_LIMIT>750000</tns:UNDWRT3_LIMIT>"+
						"<tns:ROUNDING>50</tns:ROUNDING>"+
						"<tns:KOLVO_DAYS_DO_VYDACHI>1</tns:KOLVO_DAYS_DO_VYDACHI>"+
						"<tns:HOMOGEN_PORTF_NO>11120</tns:HOMOGEN_PORTF_NO>"+
						"<tns:HOMOGEN_PORTF_NAME>Автокредит</tns:HOMOGEN_PORTF_NAME>"+
						"<tns:HOMOGEN_SUBPORTF_NO>11120</tns:HOMOGEN_SUBPORTF_NO>"+
						"<tns:HOMOGEN_SUBPORTF_NAME>Автокредит</tns:HOMOGEN_SUBPORTF_NAME>"+
						"<tns:CURRENT_RESERV_RATE>0.75</tns:CURRENT_RESERV_RATE>"+
						"<tns:DAYS_WAIT>"+dayWait+"</tns:DAYS_WAIT>"+
					"</tns:SEGMENT_RISK_1>"+
					"<tns:SEGMENT_RISK_4>"+
						"<tns:LPR_DAYS_FOR_DECISION>3</tns:LPR_DAYS_FOR_DECISION>"+
						"<tns:SPECIAL_APP>Y</tns:SPECIAL_APP>"+
					"</tns:SEGMENT_RISK_4>"+
					"<tns:SEGMENT_RISK_5>"+
						"<tns:CSKO_level_of_competence>333000</tns:CSKO_level_of_competence>"+
					"</tns:SEGMENT_RISK_5>"+
				"</tns:PARAMS_RISK>"+
				"<tns:PARAMS_RISK_TB TB_CODE=\"0\">"+
					"<tns:SEGMENT_RISK_2_TB>"+
						"<tns:FLAG_RBP>Y</tns:FLAG_RBP>"+
					"</tns:SEGMENT_RISK_2_TB>"+
					"<tns:SEGMENT_RISK_6_TB>"+
						"<tns:TRUSTEE_LOAN>1</tns:TRUSTEE_LOAN>"+
					"</tns:SEGMENT_RISK_6_TB>"+
					"<tns:SEGMENT_RISK_21_TB>"+
						"<tns:DEALER_CHANGE_ABILITY>1</tns:DEALER_CHANGE_ABILITY>"+
						"<tns:NPL_LZP_GRA>40000.0</tns:NPL_LZP_GRA>"+
						"<tns:NPL_LZP_GRA1>40000.0</tns:NPL_LZP_GRA1>"+
						"<tns:NPL_LZP_GRB>40000.0</tns:NPL_LZP_GRB>"+
						"<tns:NPL_LZP_GRC>40000.0</tns:NPL_LZP_GRC>"+
						"<tns:NPL_LZP_GRC1>40000.0</tns:NPL_LZP_GRC1>"+
						"<tns:NPL_LZP_GRD>40000.0</tns:NPL_LZP_GRD>"+
						"<tns:NPL_LZP_GRE>40000.0</tns:NPL_LZP_GRE>"+
					"</tns:SEGMENT_RISK_21_TB>"+
				"</tns:PARAMS_RISK_TB>"+
				"<tns:PARAMS_IT>"+
					"<tns:SEGMENT_IT_1>"+
						"<tns:STOP_LIST_TIMEOUT>300</tns:STOP_LIST_TIMEOUT>"+
						"<tns:STOP_LIST_RETRY_NUM>3</tns:STOP_LIST_RETRY_NUM>"+
						"<tns:HUNTER_TIMEOUT>300</tns:HUNTER_TIMEOUT>"+
						"<tns:HUNTER_RETRY_NUM>3</tns:HUNTER_RETRY_NUM>"+
						"<tns:NATIONALHUNTERTIMEOUT>300</tns:NATIONALHUNTERTIMEOUT>"+
						"<tns:NATIONALHUNTERRETRYNUM>3</tns:NATIONALHUNTERRETRYNUM>"+
						"<tns:FPSEQ_TIMEOUT>300</tns:FPSEQ_TIMEOUT>"+
						"<tns:FPSEQ_RETRY_NUM>3</tns:FPSEQ_RETRY_NUM>"+
						"<tns:ASSD_GSZ_TIMEOUT>300</tns:ASSD_GSZ_TIMEOUT>"+
						"<tns:ASSD_GSZ_RETRY_NUM>3</tns:ASSD_GSZ_RETRY_NUM>"+
						"<tns:BACK_OFFICE_TIMEOUT>300</tns:BACK_OFFICE_TIMEOUT>"+
						"<tns:BACK_OFFICE_RETRY_NUM>3</tns:BACK_OFFICE_RETRY_NUM>"+
					"</tns:SEGMENT_IT_1>"+
					"<tns:SEGMENT_IT_2>"+
						"<tns:SPOOBK_Timeout>300</tns:SPOOBK_Timeout>"+
						"<tns:SPOOBK_Retry_Num>3</tns:SPOOBK_Retry_Num>"+
					"</tns:SEGMENT_IT_2>"+
					"<tns:SEGMENT_IT_3>"+
						"<tns:MBKI_TIMEOUT_GRD>300</tns:MBKI_TIMEOUT_GRD>"+
						"<tns:MBKI_RETRY_NUM_GRD>3</tns:MBKI_RETRY_NUM_GRD>"+
						"<tns:BRS_TIMEOUT_GRD>300</tns:BRS_TIMEOUT_GRD>"+
						"<tns:BRS_RETRY_NUM_GRD>3</tns:BRS_RETRY_NUM_GRD>"+
						"<tns:COD_TIMEOUT_GRD>300</tns:COD_TIMEOUT_GRD>"+
						"<tns:COD_RETRY_NUM_GRD>3</tns:COD_RETRY_NUM_GRD>"+
						"<tns:ASSD_TIMEOUT_GRD>300</tns:ASSD_TIMEOUT_GRD>"+
						"<tns:ASSD_RETRY_NUM_GRD>3</tns:ASSD_RETRY_NUM_GRD>"+
						"<tns:BKI_GP_TIMEOUT_GRD>300</tns:BKI_GP_TIMEOUT_GRD>"+
						"<tns:BKI_GP_RETRY_NUM_GRD>3</tns:BKI_GP_RETRY_NUM_GRD>"+
						"<tns:NBKI_TIMEOUT_GRD>300</tns:NBKI_TIMEOUT_GRD>"+
						"<tns:NBKI_RETRY_NUM_GRD>3</tns:NBKI_RETRY_NUM_GRD>"+
						"<tns:BKI_EI_TIMEOUT_GRD>300</tns:BKI_EI_TIMEOUT_GRD>"+
						"<tns:BKI_EI_RETRY_NUM_GRD>3</tns:BKI_EI_RETRY_NUM_GRD>"+
						"<tns:PF_TIMEOUT_GRD>300</tns:PF_TIMEOUT_GRD>"+
						"<tns:PF_RETRY_NUM_GRD>3</tns:PF_RETRY_NUM_GRD>"+
						"<tns:FMS_TIMEOUT_GRD>300</tns:FMS_TIMEOUT_GRD>"+
						"<tns:FMS_RETRY_NUM_GROUP_D>3</tns:FMS_RETRY_NUM_GROUP_D>"+
					"</tns:SEGMENT_IT_3>"+
					"<tns:SEGMENT_IT_4>"+
						"<tns:MBKI_TIMEOUT_GRA>300</tns:MBKI_TIMEOUT_GRA>"+
						"<tns:MBKI_RETRY_NUM_GRA>3</tns:MBKI_RETRY_NUM_GRA>"+
						"<tns:MBKI_TIMEOUT_GRB>300</tns:MBKI_TIMEOUT_GRB>"+
						"<tns:MBKI_RETRY_NUM_GRB>3</tns:MBKI_RETRY_NUM_GRB>"+
						"<tns:MBKI_TIMEOUT_GRC>300</tns:MBKI_TIMEOUT_GRC>"+
						"<tns:MBKI_RETRY_NUM_GRC>3</tns:MBKI_RETRY_NUM_GRC>"+
						"<tns:MBKI_TIMEOUT_GRE>300</tns:MBKI_TIMEOUT_GRE>"+
						"<tns:MBKI_RETRY_NUM_GRE>3</tns:MBKI_RETRY_NUM_GRE>"+
						"<tns:BRS_TIMEOUT_GRA>300</tns:BRS_TIMEOUT_GRA>"+
						"<tns:BRS_RETRY_NUM_GRA>3</tns:BRS_RETRY_NUM_GRA>"+
						"<tns:BRS_TIMEOUT_GRB>300</tns:BRS_TIMEOUT_GRB>"+
						"<tns:BRS_RETRY_NUM_GRB>3</tns:BRS_RETRY_NUM_GRB>"+
						"<tns:BRS_TIMEOUT_GRC>300</tns:BRS_TIMEOUT_GRC>"+
						"<tns:BRS_RETRY_NUM_GRC>3</tns:BRS_RETRY_NUM_GRC>"+
						"<tns:BRS_TIMEOUT_GRE>300</tns:BRS_TIMEOUT_GRE>"+
						"<tns:BRS_RETRY_NUM_GRE>3</tns:BRS_RETRY_NUM_GRE>"+
						"<tns:COD_TIMEOUT_GRA>300</tns:COD_TIMEOUT_GRA>"+
						"<tns:COD_RETRY_NUM_GRA>3</tns:COD_RETRY_NUM_GRA>"+
						"<tns:COD_TIMEOUT_GRB>300</tns:COD_TIMEOUT_GRB>"+
						"<tns:COD_RETRY_NUM_GRB>3</tns:COD_RETRY_NUM_GRB>"+
						"<tns:COD_TIMEOUT_GRC>300</tns:COD_TIMEOUT_GRC>"+
						"<tns:COD_RETRY_NUM_GRC>3</tns:COD_RETRY_NUM_GRC>"+
						"<tns:COD_TIMEOUT_GRE>300</tns:COD_TIMEOUT_GRE>"+
						"<tns:COD_RETRY_NUM_GRE>3</tns:COD_RETRY_NUM_GRE>"+
						"<tns:ASSD_TIMEOUT_GRA>300</tns:ASSD_TIMEOUT_GRA>"+
						"<tns:ASSD_RETRY_NUM_GRA>3</tns:ASSD_RETRY_NUM_GRA>"+
						"<tns:ASSD_TIMEOUT_GRB>300</tns:ASSD_TIMEOUT_GRB>"+
						"<tns:ASSD_RETRY_NUM_GRB>3</tns:ASSD_RETRY_NUM_GRB>"+
						"<tns:ASSD_TIMEOUT_GRC>300</tns:ASSD_TIMEOUT_GRC>"+
						"<tns:ASSD_RETRY_NUM_GRC>3</tns:ASSD_RETRY_NUM_GRC>"+
						"<tns:ASSD_TIMEOUT_GRE>300</tns:ASSD_TIMEOUT_GRE>"+
						"<tns:ASSD_RETRY_NUM_GRE>3</tns:ASSD_RETRY_NUM_GRE>"+
						"<tns:BKI_GP_TIMEOUT_GRA>300</tns:BKI_GP_TIMEOUT_GRA>"+
						"<tns:BKI_GP_RETRY_NUM_GRA>3</tns:BKI_GP_RETRY_NUM_GRA>"+
						"<tns:BKI_GP_TIMEOUT_GRB>300</tns:BKI_GP_TIMEOUT_GRB>"+
						"<tns:BKI_GP_RETRY_NUM_GRB>3</tns:BKI_GP_RETRY_NUM_GRB>"+
						"<tns:BKI_GP_TIMEOUT_GRC>300</tns:BKI_GP_TIMEOUT_GRC>"+
						"<tns:BKI_GP_RETRY_NUM_GRC>3</tns:BKI_GP_RETRY_NUM_GRC>"+
						"<tns:BKI_GP_TIMEOUT_GRE>300</tns:BKI_GP_TIMEOUT_GRE>"+
						"<tns:BKI_GP_RETRY_NUM_GRE>3</tns:BKI_GP_RETRY_NUM_GRE>"+
						"<tns:NBKI_TIMEOUT_GRA>300</tns:NBKI_TIMEOUT_GRA>"+
						"<tns:NBKI_RETRY_NUM_GRA>3</tns:NBKI_RETRY_NUM_GRA>"+
						"<tns:NBKI_TIMEOUT_GRB>300</tns:NBKI_TIMEOUT_GRB>"+
						"<tns:NBKI_RETRY_NUM_GRB>3</tns:NBKI_RETRY_NUM_GRB>"+
						"<tns:NBKI_TIMEOUT_GRC>300</tns:NBKI_TIMEOUT_GRC>"+
						"<tns:NBKI_RETRY_NUM_GRC>3</tns:NBKI_RETRY_NUM_GRC>"+
						"<tns:NBKI_TIMEOUT_GRE>300</tns:NBKI_TIMEOUT_GRE>"+
						"<tns:NBKI_RETRY_NUM_GRE>3</tns:NBKI_RETRY_NUM_GRE>"+
						"<tns:BKI_EI_TIMEOUT_GRA>300</tns:BKI_EI_TIMEOUT_GRA>"+
						"<tns:BKI_EI_RETRY_NUM_GRA>3</tns:BKI_EI_RETRY_NUM_GRA>"+
						"<tns:BKI_EI_TIMEOUT_GRB>300</tns:BKI_EI_TIMEOUT_GRB>"+
						"<tns:BKI_EI_RETRY_NUM_GRB>3</tns:BKI_EI_RETRY_NUM_GRB>"+
						"<tns:BKI_EI_TIMEOUT_GRC>300</tns:BKI_EI_TIMEOUT_GRC>"+
						"<tns:BKI_EI_RETRY_NUM_GRC>3</tns:BKI_EI_RETRY_NUM_GRC>"+
						"<tns:BKI_EI_TIMEOUT_GRE>300</tns:BKI_EI_TIMEOUT_GRE>"+
						"<tns:BKI_EI_RETRY_NUM_GRE>3</tns:BKI_EI_RETRY_NUM_GRE>"+
						"<tns:PF_TIMEOUT_GRA>300</tns:PF_TIMEOUT_GRA>"+
						"<tns:PF_RETRY_NUM_GRA>3</tns:PF_RETRY_NUM_GRA>"+
						"<tns:PF_TIMEOUT_GRB>300</tns:PF_TIMEOUT_GRB>"+
						"<tns:PF_RETRY_NUM_GRB>3</tns:PF_RETRY_NUM_GRB>"+
						"<tns:PF_TIMEOUT_GRC>300</tns:PF_TIMEOUT_GRC>"+
						"<tns:PF_RETRY_NUM_GRC>3</tns:PF_RETRY_NUM_GRC>"+
						"<tns:PF_TIMEOUT_GRE>300</tns:PF_TIMEOUT_GRE>"+
						"<tns:PF_RETRY_NUM_GRE>3</tns:PF_RETRY_NUM_GRE>"+
						"<tns:FMS_TIMEOUT_GRA>300</tns:FMS_TIMEOUT_GRA>"+
						"<tns:FMS_RETRY_NUM_GROUP_A>3</tns:FMS_RETRY_NUM_GROUP_A>"+
						"<tns:FMS_TIMEOUT_GRB>300</tns:FMS_TIMEOUT_GRB>"+
						"<tns:FMS_RETRY_NUM_GROUP_B>3</tns:FMS_RETRY_NUM_GROUP_B>"+
						"<tns:FMS_TIMEOUT_GRC>300</tns:FMS_TIMEOUT_GRC>"+
						"<tns:FMS_RETRY_NUM_GROUP_C>3</tns:FMS_RETRY_NUM_GROUP_C>"+
						"<tns:FMS_TIMEOUT_GRE>300</tns:FMS_TIMEOUT_GRE>"+
						"<tns:FMS_RETRY_NUM_GROUP_E>3</tns:FMS_RETRY_NUM_GROUP_E>"+
					"</tns:SEGMENT_IT_4>"+
				"</tns:PARAMS_IT>"+
				"<tns:PARAMS_SYS_TB TB_CODE=\"0\">"+
					"<tns:SEGMENT_SYS_1_TB>"+
						"<tns:STOP_LIST>Y</tns:STOP_LIST>"+
						"<tns:HUNTER>Y</tns:HUNTER>"+
						"<tns:NATIONALHUNTER>Y</tns:NATIONALHUNTER>"+
						"<tns:FPSEQ>Y</tns:FPSEQ>"+
						"<tns:BRS_EGRUL>Y</tns:BRS_EGRUL>"+
						"<tns:AS_SD_GZS>Y</tns:AS_SD_GZS>"+
					"</tns:SEGMENT_SYS_1_TB>"+
					"<tns:SEGMENT_SYS_2_TB>"+
						"<tns:SPOOBK>Y</tns:SPOOBK>"+
					"</tns:SEGMENT_SYS_2_TB>"+
					"<tns:SEGMENT_SYS_4_TB>"+
						"<tns:MBKI_GRD>Y</tns:MBKI_GRD>"+
						"<tns:BRS_GRD>Y</tns:BRS_GRD>"+
						"<tns:COD_GRD>Y</tns:COD_GRD>"+
						"<tns:AS_SD_GRD>Y</tns:AS_SD_GRD>"+
						"<tns:CB_GLPAY_GRD>Y</tns:CB_GLPAY_GRD>"+
						"<tns:CB_NBKI_GRD>Y</tns:CB_NBKI_GRD>"+
						"<tns:CB_EXPINT_GRD>Y</tns:CB_EXPINT_GRD>"+
						"<tns:PFR_GRD>Y</tns:PFR_GRD>"+
						"<tns:FMS_GRD>Y</tns:FMS_GRD>"+
					"</tns:SEGMENT_SYS_4_TB>"+
					"<tns:SEGMENT_SYS_5_TB>"+
						"<tns:MBKI_GRA>Y</tns:MBKI_GRA>"+
						"<tns:MBKI_GRB>Y</tns:MBKI_GRB>"+
						"<tns:MBKI_GRC>Y</tns:MBKI_GRC>"+
						"<tns:MBKI_GRE>Y</tns:MBKI_GRE>"+
						"<tns:BRS_GRA>Y</tns:BRS_GRA>"+
						"<tns:BRS_GRB>Y</tns:BRS_GRB>"+
						"<tns:BRS_GRC>Y</tns:BRS_GRC>"+
						"<tns:BRS_GRE>Y</tns:BRS_GRE>"+
						"<tns:COD_GRA>Y</tns:COD_GRA>"+
						"<tns:COD_GRB>Y</tns:COD_GRB>"+
						"<tns:COD_GRC>N</tns:COD_GRC>"+
						"<tns:COD_GRE>N</tns:COD_GRE>"+
						"<tns:AS_SD_GRA>N</tns:AS_SD_GRA>"+
						"<tns:AS_SD_GRB>N</tns:AS_SD_GRB>"+
						"<tns:AS_SD_GRC>N</tns:AS_SD_GRC>"+
						"<tns:AS_SD_GRE>N</tns:AS_SD_GRE>"+
						"<tns:CB_GLPAY_GRA>N</tns:CB_GLPAY_GRA>"+
						"<tns:CB_GLPAY_GRB>N</tns:CB_GLPAY_GRB>"+
						"<tns:CB_GLPAY_GRC>N</tns:CB_GLPAY_GRC>"+
						"<tns:CB_GLPAY_GRE>N</tns:CB_GLPAY_GRE>"+
						"<tns:CB_NBKI_GRA>N</tns:CB_NBKI_GRA>"+
						"<tns:CB_NBKI_GRB>N</tns:CB_NBKI_GRB>"+
						"<tns:CB_NBKI_GRC>N</tns:CB_NBKI_GRC>"+
						"<tns:CB_NBKI_GRE>N</tns:CB_NBKI_GRE>"+
						"<tns:CB_EXPINT_GRA>N</tns:CB_EXPINT_GRA>"+
						"<tns:CB_EXPINT_GRB>N</tns:CB_EXPINT_GRB>"+
						"<tns:CB_EXPINT_GRC>N</tns:CB_EXPINT_GRC>"+
						"<tns:CB_EXPINT_GRE>N</tns:CB_EXPINT_GRE>"+
						"<tns:PFR_GRA>N</tns:PFR_GRA>"+
						"<tns:PFR_GRB>N</tns:PFR_GRB>"+
						"<tns:PFR_GRC>N</tns:PFR_GRC>"+
						"<tns:PFR_GRE>N</tns:PFR_GRE>"+
						"<tns:FMS_GRA>N</tns:FMS_GRA>"+
						"<tns:FMS_GRB>N</tns:FMS_GRB>"+
						"<tns:FMS_GRC>N</tns:FMS_GRC>"+
						"<tns:FMS_GRE>N</tns:FMS_GRE>"+
					"</tns:SEGMENT_SYS_5_TB>"+
				"</tns:PARAMS_SYS_TB>"+
				"<tns:PARAMS_SERVICE>"+
					"<tns:SEGMENT_SERVICE_1>"+
						"<tns:MIN_INTRATE>15.0</tns:MIN_INTRATE>"+
						"<tns:MAX_INTRATE>75.0</tns:MAX_INTRATE>"+
					"</tns:SEGMENT_SERVICE_1>"+
				"</tns:PARAMS_SERVICE>"+
				"<tns:PARAMS_TARIFF>"+
					"<tns:SEGMENT_TARIFF_1>"+
						"<tns:SUBPRODUCT_VERSION>1</tns:SUBPRODUCT_VERSION>"+
						"<tns:VALID_FROM>24042014</tns:VALID_FROM>"+
						"<tns:VALID_TO>01042015</tns:VALID_TO>"+
						"<tns:ACT_SCHEMA_CODE>11188</tns:ACT_SCHEMA_CODE>"+
						"<tns:ACT_SCHEMA_NAME>назв акц схем</tns:ACT_SCHEMA_NAME>"+
					"</tns:SEGMENT_TARIFF_1>"+
					"<tns:SEGMENT_TARIFF_2>"+
						"<tns:MIN_TERM>3</tns:MIN_TERM>"+
						"<tns:MAX_TERM>60</tns:MAX_TERM>"+
					"</tns:SEGMENT_TARIFF_2>"+
					"<tns:SEGMENT_TARIFF_3>"+
						"<tns:CREDIT_RANGE_1_MONTHS>12</tns:CREDIT_RANGE_1_MONTHS>"+
						"<tns:CREDIT_RANGE_2_MONTHS>24</tns:CREDIT_RANGE_2_MONTHS>"+
					"</tns:SEGMENT_TARIFF_3>"+
					"<tns:SEGMENT_TARIFF_21>"+
						"<tns:MIN_DOWNPAYMENT_IN_PERC>15.0</tns:MIN_DOWNPAYMENT_IN_PERC>"+
						"<tns:AUTO_GRA_NEW_R0_FP0>0.1</tns:AUTO_GRA_NEW_R0_FP0>"+
						"<tns:AUTO_GRA_NEW_R0_FP1>0.11</tns:AUTO_GRA_NEW_R0_FP1>"+
						"<tns:AUTO_GRA_NEW_R0_FP2>0.12</tns:AUTO_GRA_NEW_R0_FP2>"+
						"<tns:AUTO_GRA_NEW_R1_FP0>0.13</tns:AUTO_GRA_NEW_R1_FP0>"+
						"<tns:AUTO_GRA_NEW_R1_FP1>0.14</tns:AUTO_GRA_NEW_R1_FP1>"+
						"<tns:AUTO_GRA_NEW_R1_FP2>0.15</tns:AUTO_GRA_NEW_R1_FP2>"+
						"<tns:AUTO_GRA_NEW_R2_FP0>0.16</tns:AUTO_GRA_NEW_R2_FP0>"+
						"<tns:AUTO_GRA_NEW_R2_FP1>0.17</tns:AUTO_GRA_NEW_R2_FP1>"+
						"<tns:AUTO_GRA_NEW_R2_FP2>0.18</tns:AUTO_GRA_NEW_R2_FP2>"+
						"<tns:AUTO_GRA1_NEW_R0_FP0>0.19</tns:AUTO_GRA1_NEW_R0_FP0>"+
						"<tns:AUTO_GRA1_NEW_R0_FP1>0.2</tns:AUTO_GRA1_NEW_R0_FP1>"+
						"<tns:AUTO_GRA1_NEW_R0_FP2>0.21</tns:AUTO_GRA1_NEW_R0_FP2>"+
						"<tns:AUTO_GRA1_NEW_R1_FP0>0.22</tns:AUTO_GRA1_NEW_R1_FP0>"+
						"<tns:AUTO_GRA1_NEW_R1_FP1>0.23</tns:AUTO_GRA1_NEW_R1_FP1>"+
						"<tns:AUTO_GRA1_NEW_R1_FP2>0.24</tns:AUTO_GRA1_NEW_R1_FP2>"+
						"<tns:AUTO_GRA1_NEW_R2_FP0>0.25</tns:AUTO_GRA1_NEW_R2_FP0>"+
						"<tns:AUTO_GRA1_NEW_R2_FP1>0.26</tns:AUTO_GRA1_NEW_R2_FP1>"+
						"<tns:AUTO_GRA1_NEW_R2_FP2>0.27</tns:AUTO_GRA1_NEW_R2_FP2>"+
						"<tns:AUTO_GRB_NEW_R0_FP0>0.28</tns:AUTO_GRB_NEW_R0_FP0>"+
						"<tns:AUTO_GRB_NEW_R0_FP1>0.29</tns:AUTO_GRB_NEW_R0_FP1>"+
						"<tns:AUTO_GRB_NEW_R0_FP2>0.3</tns:AUTO_GRB_NEW_R0_FP2>"+
						"<tns:AUTO_GRB_NEW_R1_FP0>0.31</tns:AUTO_GRB_NEW_R1_FP0>"+
						"<tns:AUTO_GRB_NEW_R1_FP1>0.32</tns:AUTO_GRB_NEW_R1_FP1>"+
						"<tns:AUTO_GRB_NEW_R1_FP2>0.33</tns:AUTO_GRB_NEW_R1_FP2>"+
						"<tns:AUTO_GRB_NEW_R2_FP0>0.34</tns:AUTO_GRB_NEW_R2_FP0>"+
						"<tns:AUTO_GRB_NEW_R2_FP1>0.35</tns:AUTO_GRB_NEW_R2_FP1>"+
						"<tns:AUTO_GRB_NEW_R2_FP2>0.36</tns:AUTO_GRB_NEW_R2_FP2>"+
						"<tns:AUTO_GRC_NEW_R0_FP0>0.46</tns:AUTO_GRC_NEW_R0_FP0>"+
						"<tns:AUTO_GRC_NEW_R0_FP1>0.47</tns:AUTO_GRC_NEW_R0_FP1>"+
						"<tns:AUTO_GRC_NEW_R0_FP2>0.48</tns:AUTO_GRC_NEW_R0_FP2>"+
						"<tns:AUTO_GRC_NEW_R1_FP0>0.49</tns:AUTO_GRC_NEW_R1_FP0>"+
						"<tns:AUTO_GRC_NEW_R1_FP1>0.5</tns:AUTO_GRC_NEW_R1_FP1>"+
						"<tns:AUTO_GRC_NEW_R1_FP2>0.51</tns:AUTO_GRC_NEW_R1_FP2>"+
						"<tns:AUTO_GRC_NEW_R2_FP0>0.52</tns:AUTO_GRC_NEW_R2_FP0>"+
						"<tns:AUTO_GRC_NEW_R2_FP1>0.53</tns:AUTO_GRC_NEW_R2_FP1>"+
						"<tns:AUTO_GRC_NEW_R2_FP2>0.54</tns:AUTO_GRC_NEW_R2_FP2>"+
						"<tns:AUTO_GRC1_NEW_R0_FP0>0.37</tns:AUTO_GRC1_NEW_R0_FP0>"+
						"<tns:AUTO_GRC1_NEW_R0_FP1>0.38</tns:AUTO_GRC1_NEW_R0_FP1>"+
						"<tns:AUTO_GRC1_NEW_R0_FP2>0.39</tns:AUTO_GRC1_NEW_R0_FP2>"+
						"<tns:AUTO_GRC1_NEW_R1_FP0>0.4</tns:AUTO_GRC1_NEW_R1_FP0>"+
						"<tns:AUTO_GRC1_NEW_R1_FP1>0.41</tns:AUTO_GRC1_NEW_R1_FP1>"+
						"<tns:AUTO_GRC1_NEW_R1_FP2>0.42</tns:AUTO_GRC1_NEW_R1_FP2>"+
						"<tns:AUTO_GRC1_NEW_R2_FP0>0.43</tns:AUTO_GRC1_NEW_R2_FP0>"+
						"<tns:AUTO_GRC1_NEW_R2_FP1>0.44</tns:AUTO_GRC1_NEW_R2_FP1>"+
						"<tns:AUTO_GRC1_NEW_R2_FP2>0.45</tns:AUTO_GRC1_NEW_R2_FP2>"+
						"<tns:AUTO_GRD_NEW_R0_FP0>0.55</tns:AUTO_GRD_NEW_R0_FP0>"+
						"<tns:AUTO_GRD_NEW_R0_FP1>0.56</tns:AUTO_GRD_NEW_R0_FP1>"+
						"<tns:AUTO_GRD_NEW_R0_FP2>0.57</tns:AUTO_GRD_NEW_R0_FP2>"+
						"<tns:AUTO_GRD_NEW_R1_FP0>0.58</tns:AUTO_GRD_NEW_R1_FP0>"+
						"<tns:AUTO_GRD_NEW_R1_FP1>0.59</tns:AUTO_GRD_NEW_R1_FP1>"+
						"<tns:AUTO_GRD_NEW_R1_FP2>0.6</tns:AUTO_GRD_NEW_R1_FP2>"+
						"<tns:AUTO_GRD_NEW_R2_FP0>0.61</tns:AUTO_GRD_NEW_R2_FP0>"+
						"<tns:AUTO_GRD_NEW_R2_FP1>0.62</tns:AUTO_GRD_NEW_R2_FP1>"+
						"<tns:AUTO_GRD_NEW_R2_FP2>0.63</tns:AUTO_GRD_NEW_R2_FP2>"+
						"<tns:AUTO_GRE_NEW_R0_FP0>0.64</tns:AUTO_GRE_NEW_R0_FP0>"+
						"<tns:AUTO_GRE_NEW_R0_FP1>0.65</tns:AUTO_GRE_NEW_R0_FP1>"+
						"<tns:AUTO_GRE_NEW_R0_FP2>0.66</tns:AUTO_GRE_NEW_R0_FP2>"+
						"<tns:AUTO_GRE_NEW_R1_FP0>0.67</tns:AUTO_GRE_NEW_R1_FP0>"+
						"<tns:AUTO_GRE_NEW_R1_FP1>0.68</tns:AUTO_GRE_NEW_R1_FP1>"+
						"<tns:AUTO_GRE_NEW_R1_FP2>0.69</tns:AUTO_GRE_NEW_R1_FP2>"+
						"<tns:AUTO_GRE_NEW_R2_FP0>0.7</tns:AUTO_GRE_NEW_R2_FP0>"+
						"<tns:AUTO_GRE_NEW_R2_FP1>0.71</tns:AUTO_GRE_NEW_R2_FP1>"+
						"<tns:AUTO_GRE_NEW_R2_FP2>0.72</tns:AUTO_GRE_NEW_R2_FP2>"+
						"<tns:AUTO_GRA_GKH_R0_FP0>0.8</tns:AUTO_GRA_GKH_R0_FP0>"+
						"<tns:AUTO_GRA_GKH_R0_FP1>0.81</tns:AUTO_GRA_GKH_R0_FP1>"+
						"<tns:AUTO_GRA_GKH_R0_FP2>0.82</tns:AUTO_GRA_GKH_R0_FP2>"+
						"<tns:AUTO_GRA_GKH_R1_FP0>0.83</tns:AUTO_GRA_GKH_R1_FP0>"+
						"<tns:AUTO_GRA_GKH_R1_FP1>0.84</tns:AUTO_GRA_GKH_R1_FP1>"+
						"<tns:AUTO_GRA_GKH_R1_FP2>0.85</tns:AUTO_GRA_GKH_R1_FP2>"+
						"<tns:AUTO_GRA_GKH_R2_FP0>0.86</tns:AUTO_GRA_GKH_R2_FP0>"+
						"<tns:AUTO_GRA_GKH_R2_FP1>0.87</tns:AUTO_GRA_GKH_R2_FP1>"+
						"<tns:AUTO_GRA_GKH_R2_FP2>0.88</tns:AUTO_GRA_GKH_R2_FP2>"+
						"<tns:AUTO_GRA1_GKH_R0_FP0>0.89</tns:AUTO_GRA1_GKH_R0_FP0>"+
						"<tns:AUTO_GRA1_GKH_R0_FP1>0.9</tns:AUTO_GRA1_GKH_R0_FP1>"+
						"<tns:AUTO_GRA1_GKH_R0_FP2>0.91</tns:AUTO_GRA1_GKH_R0_FP2>"+
						"<tns:AUTO_GRA1_GKH_R1_FP0>0.92</tns:AUTO_GRA1_GKH_R1_FP0>"+
						"<tns:AUTO_GRA1_GKH_R1_FP1>0.93</tns:AUTO_GRA1_GKH_R1_FP1>"+
						"<tns:AUTO_GRA1_GKH_R1_FP2>0.94</tns:AUTO_GRA1_GKH_R1_FP2>"+
						"<tns:AUTO_GRA1_GKH_R2_FP0>0.95</tns:AUTO_GRA1_GKH_R2_FP0>"+
						"<tns:AUTO_GRA1_GKH_R2_FP1>0.96</tns:AUTO_GRA1_GKH_R2_FP1>"+
						"<tns:AUTO_GRA1_GKH_R2_FP2>0.97</tns:AUTO_GRA1_GKH_R2_FP2>"+
						"<tns:AUTO_GRB_GKH_R0_FP0>0.98</tns:AUTO_GRB_GKH_R0_FP0>"+
						"<tns:AUTO_GRB_GKH_R0_FP1>0.99</tns:AUTO_GRB_GKH_R0_FP1>"+
						"<tns:AUTO_GRB_GKH_R0_FP2>1.1</tns:AUTO_GRB_GKH_R0_FP2>"+
						"<tns:AUTO_GRB_GKH_R1_FP0>1.11</tns:AUTO_GRB_GKH_R1_FP0>"+
						"<tns:AUTO_GRB_GKH_R1_FP1>1.12</tns:AUTO_GRB_GKH_R1_FP1>"+
						"<tns:AUTO_GRB_GKH_R1_FP2>1.13</tns:AUTO_GRB_GKH_R1_FP2>"+
						"<tns:AUTO_GRB_GKH_R2_FP0>1.14</tns:AUTO_GRB_GKH_R2_FP0>"+
						"<tns:AUTO_GRB_GKH_R2_FP1>1.15</tns:AUTO_GRB_GKH_R2_FP1>"+
						"<tns:AUTO_GRB_GKH_R2_FP2>1.16</tns:AUTO_GRB_GKH_R2_FP2>"+
						"<tns:AUTO_GRC_GKH_R0_FP0>1.26</tns:AUTO_GRC_GKH_R0_FP0>"+
						"<tns:AUTO_GRC_GKH_R0_FP1>1.27</tns:AUTO_GRC_GKH_R0_FP1>"+
						"<tns:AUTO_GRC_GKH_R0_FP2>1.28</tns:AUTO_GRC_GKH_R0_FP2>"+
						"<tns:AUTO_GRC_GKH_R1_FP0>1.29</tns:AUTO_GRC_GKH_R1_FP0>"+
						"<tns:AUTO_GRC_GKH_R1_FP1>1.3</tns:AUTO_GRC_GKH_R1_FP1>"+
						"<tns:AUTO_GRC_GKH_R1_FP2>1.31</tns:AUTO_GRC_GKH_R1_FP2>"+
						"<tns:AUTO_GRC_GKH_R2_FP0>1.32</tns:AUTO_GRC_GKH_R2_FP0>"+
						"<tns:AUTO_GRC_GKH_R2_FP1>1.33</tns:AUTO_GRC_GKH_R2_FP1>"+
						"<tns:AUTO_GRC_GKH_R2_FP2>1.34</tns:AUTO_GRC_GKH_R2_FP2>"+
						"<tns:AUTO_GRC1_GKH_R0_FP0>1.17</tns:AUTO_GRC1_GKH_R0_FP0>"+
						"<tns:AUTO_GRC1_GKH_R0_FP1>1.18</tns:AUTO_GRC1_GKH_R0_FP1>"+
						"<tns:AUTO_GRC1_GKH_R0_FP2>1.19</tns:AUTO_GRC1_GKH_R0_FP2>"+
						"<tns:AUTO_GRC1_GKH_R1_FP0>1.2</tns:AUTO_GRC1_GKH_R1_FP0>"+
						"<tns:AUTO_GRC1_GKH_R1_FP1>1.21</tns:AUTO_GRC1_GKH_R1_FP1>"+
						"<tns:AUTO_GRC1_GKH_R1_FP2>1.22</tns:AUTO_GRC1_GKH_R1_FP2>"+
						"<tns:AUTO_GRC1_GKH_R2_FP0>1.23</tns:AUTO_GRC1_GKH_R2_FP0>"+
						"<tns:AUTO_GRC1_GKH_R2_FP1>1.24</tns:AUTO_GRC1_GKH_R2_FP1>"+
						"<tns:AUTO_GRC1_GKH_R2_FP2>1.25</tns:AUTO_GRC1_GKH_R2_FP2>"+
						"<tns:AUTO_GRD_GKH_R0_FP0>1.35</tns:AUTO_GRD_GKH_R0_FP0>"+
						"<tns:AUTO_GRD_GKH_R0_FP1>1.36</tns:AUTO_GRD_GKH_R0_FP1>"+
						"<tns:AUTO_GRD_GKH_R0_FP2>1.37</tns:AUTO_GRD_GKH_R0_FP2>"+
						"<tns:AUTO_GRD_GKH_R1_FP0>1.38</tns:AUTO_GRD_GKH_R1_FP0>"+
						"<tns:AUTO_GRD_GKH_R1_FP1>1.39</tns:AUTO_GRD_GKH_R1_FP1>"+
						"<tns:AUTO_GRD_GKH_R1_FP2>1.4</tns:AUTO_GRD_GKH_R1_FP2>"+
						"<tns:AUTO_GRD_GKH_R2_FP0>1.41</tns:AUTO_GRD_GKH_R2_FP0>"+
						"<tns:AUTO_GRD_GKH_R2_FP1>1.42</tns:AUTO_GRD_GKH_R2_FP1>"+
						"<tns:AUTO_GRD_GKH_R2_FP2>1.43</tns:AUTO_GRD_GKH_R2_FP2>"+
						"<tns:AUTO_GRE_GKH_R0_FP0>1.44</tns:AUTO_GRE_GKH_R0_FP0>"+
						"<tns:AUTO_GRE_GKH_R0_FP1>1.45</tns:AUTO_GRE_GKH_R0_FP1>"+
						"<tns:AUTO_GRE_GKH_R0_FP2>1.46</tns:AUTO_GRE_GKH_R0_FP2>"+
						"<tns:AUTO_GRE_GKH_R1_FP0>1.47</tns:AUTO_GRE_GKH_R1_FP0>"+
						"<tns:AUTO_GRE_GKH_R1_FP1>1.48</tns:AUTO_GRE_GKH_R1_FP1>"+
						"<tns:AUTO_GRE_GKH_R1_FP2>1.49</tns:AUTO_GRE_GKH_R1_FP2>"+
						"<tns:AUTO_GRE_GKH_R2_FP0>1.5</tns:AUTO_GRE_GKH_R2_FP0>"+
						"<tns:AUTO_GRE_GKH_R2_FP1>1.51</tns:AUTO_GRE_GKH_R2_FP1>"+
						"<tns:AUTO_GRE_GKH_R2_FP2>1.52</tns:AUTO_GRE_GKH_R2_FP2>"+
						"<tns:AUTO_GRA_USED_R0_FP0>1.6</tns:AUTO_GRA_USED_R0_FP0>"+
						"<tns:AUTO_GRA_USED_R0_FP1>1.61</tns:AUTO_GRA_USED_R0_FP1>"+
						"<tns:AUTO_GRA_USED_R0_FP2>1.62</tns:AUTO_GRA_USED_R0_FP2>"+
						"<tns:AUTO_GRA_USED_R1_FP0>1.63</tns:AUTO_GRA_USED_R1_FP0>"+
						"<tns:AUTO_GRA_USED_R1_FP1>1.64</tns:AUTO_GRA_USED_R1_FP1>"+
						"<tns:AUTO_GRA_USED_R1_FP2>1.65</tns:AUTO_GRA_USED_R1_FP2>"+
						"<tns:AUTO_GRA_USED_R2_FP0>1.66</tns:AUTO_GRA_USED_R2_FP0>"+
						"<tns:AUTO_GRA_USED_R2_FP1>1.67</tns:AUTO_GRA_USED_R2_FP1>"+
						"<tns:AUTO_GRA_USED_R2_FP2>1.68</tns:AUTO_GRA_USED_R2_FP2>"+
						"<tns:AUTO_GRA1_USED_R0_FP0>1.69</tns:AUTO_GRA1_USED_R0_FP0>"+
						"<tns:AUTO_GRA1_USED_R0_FP1>1.7</tns:AUTO_GRA1_USED_R0_FP1>"+
						"<tns:AUTO_GRA1_USED_R0_FP2>1.71</tns:AUTO_GRA1_USED_R0_FP2>"+
						"<tns:AUTO_GRA1_USED_R1_FP0>1.72</tns:AUTO_GRA1_USED_R1_FP0>"+
						"<tns:AUTO_GRA1_USED_R1_FP1>1.73</tns:AUTO_GRA1_USED_R1_FP1>"+
						"<tns:AUTO_GRA1_USED_R1_FP2>1.74</tns:AUTO_GRA1_USED_R1_FP2>"+
						"<tns:AUTO_GRA1_USED_R2_FP0>1.75</tns:AUTO_GRA1_USED_R2_FP0>"+
						"<tns:AUTO_GRA1_USED_R2_FP1>1.76</tns:AUTO_GRA1_USED_R2_FP1>"+
						"<tns:AUTO_GRA1_USED_R2_FP2>1.77</tns:AUTO_GRA1_USED_R2_FP2>"+
						"<tns:AUTO_GRB_USED_R0_FP0>1.78</tns:AUTO_GRB_USED_R0_FP0>"+
						"<tns:AUTO_GRB_USED_R0_FP1>1.79</tns:AUTO_GRB_USED_R0_FP1>"+
						"<tns:AUTO_GRB_USED_R0_FP2>1.8</tns:AUTO_GRB_USED_R0_FP2>"+
						"<tns:AUTO_GRB_USED_R1_FP0>1.81</tns:AUTO_GRB_USED_R1_FP0>"+
						"<tns:AUTO_GRB_USED_R1_FP1>1.82</tns:AUTO_GRB_USED_R1_FP1>"+
						"<tns:AUTO_GRB_USED_R1_FP2>1.83</tns:AUTO_GRB_USED_R1_FP2>"+
						"<tns:AUTO_GRB_USED_R2_FP0>1.84</tns:AUTO_GRB_USED_R2_FP0>"+
						"<tns:AUTO_GRB_USED_R2_FP1>1.85</tns:AUTO_GRB_USED_R2_FP1>"+
						"<tns:AUTO_GRB_USED_R2_FP2>1.86</tns:AUTO_GRB_USED_R2_FP2>"+
						"<tns:AUTO_GRC_USED_R0_FP0>1.96</tns:AUTO_GRC_USED_R0_FP0>"+
						"<tns:AUTO_GRC_USED_R0_FP1>1.97</tns:AUTO_GRC_USED_R0_FP1>"+
						"<tns:AUTO_GRC_USED_R0_FP2>1.98</tns:AUTO_GRC_USED_R0_FP2>"+
						"<tns:AUTO_GRC_USED_R1_FP0>1.99</tns:AUTO_GRC_USED_R1_FP0>"+
						"<tns:AUTO_GRC_USED_R1_FP1>2.1</tns:AUTO_GRC_USED_R1_FP1>"+
						"<tns:AUTO_GRC_USED_R1_FP2>2.11</tns:AUTO_GRC_USED_R1_FP2>"+
						"<tns:AUTO_GRC_USED_R2_FP0>2.12</tns:AUTO_GRC_USED_R2_FP0>"+
						"<tns:AUTO_GRC_USED_R2_FP1>2.13</tns:AUTO_GRC_USED_R2_FP1>"+
						"<tns:AUTO_GRC_USED_R2_FP2>2.14</tns:AUTO_GRC_USED_R2_FP2>"+
						"<tns:AUTO_GRC1_USED_R0_FP0>1.87</tns:AUTO_GRC1_USED_R0_FP0>"+
						"<tns:AUTO_GRC1_USED_R0_FP1>1.88</tns:AUTO_GRC1_USED_R0_FP1>"+
						"<tns:AUTO_GRC1_USED_R0_FP2>1.89</tns:AUTO_GRC1_USED_R0_FP2>"+
						"<tns:AUTO_GRC1_USED_R1_FP0>1.9</tns:AUTO_GRC1_USED_R1_FP0>"+
						"<tns:AUTO_GRC1_USED_R1_FP1>1.91</tns:AUTO_GRC1_USED_R1_FP1>"+
						"<tns:AUTO_GRC1_USED_R1_FP2>1.92</tns:AUTO_GRC1_USED_R1_FP2>"+
						"<tns:AUTO_GRC1_USED_R2_FP0>1.93</tns:AUTO_GRC1_USED_R2_FP0>"+
						"<tns:AUTO_GRC1_USED_R2_FP1>1.94</tns:AUTO_GRC1_USED_R2_FP1>"+
						"<tns:AUTO_GRC1_USED_R2_FP2>1.95</tns:AUTO_GRC1_USED_R2_FP2>"+
						"<tns:AUTO_GRD_USED_R0_FP0>2.15</tns:AUTO_GRD_USED_R0_FP0>"+
						"<tns:AUTO_GRD_USED_R0_FP1>2.16</tns:AUTO_GRD_USED_R0_FP1>"+
						"<tns:AUTO_GRD_USED_R0_FP2>2.17</tns:AUTO_GRD_USED_R0_FP2>"+
						"<tns:AUTO_GRD_USED_R1_FP0>2.18</tns:AUTO_GRD_USED_R1_FP0>"+
						"<tns:AUTO_GRD_USED_R1_FP1>2.19</tns:AUTO_GRD_USED_R1_FP1>"+
						"<tns:AUTO_GRD_USED_R1_FP2>2.2</tns:AUTO_GRD_USED_R1_FP2>"+
						"<tns:AUTO_GRD_USED_R2_FP0>2.21</tns:AUTO_GRD_USED_R2_FP0>"+
						"<tns:AUTO_GRD_USED_R2_FP1>2.22</tns:AUTO_GRD_USED_R2_FP1>"+
						"<tns:AUTO_GRD_USED_R2_FP2>2.23</tns:AUTO_GRD_USED_R2_FP2>"+
						"<tns:AUTO_GRE_USED_R0_FP0>2.24</tns:AUTO_GRE_USED_R0_FP0>"+
						"<tns:AUTO_GRE_USED_R0_FP1>2.25</tns:AUTO_GRE_USED_R0_FP1>"+
						"<tns:AUTO_GRE_USED_R0_FP2>2.26</tns:AUTO_GRE_USED_R0_FP2>"+
						"<tns:AUTO_GRE_USED_R1_FP0>2.27</tns:AUTO_GRE_USED_R1_FP0>"+
						"<tns:AUTO_GRE_USED_R1_FP1>2.28</tns:AUTO_GRE_USED_R1_FP1>"+
						"<tns:AUTO_GRE_USED_R1_FP2>2.29</tns:AUTO_GRE_USED_R1_FP2>"+
						"<tns:AUTO_GRE_USED_R2_FP0>2.3</tns:AUTO_GRE_USED_R2_FP0>"+
						"<tns:AUTO_GRE_USED_R2_FP1>2.31</tns:AUTO_GRE_USED_R2_FP1>"+
						"<tns:AUTO_GRE_USED_R2_FP2>2.32</tns:AUTO_GRE_USED_R2_FP2>"+
						"<tns:Auto_GRA_Used_Good_KH_R0_FP0>2.4</tns:Auto_GRA_Used_Good_KH_R0_FP0>"+
						"<tns:Auto_GRA_Used_Good_KH_R0_FP1>2.41</tns:Auto_GRA_Used_Good_KH_R0_FP1>"+
						"<tns:Auto_GRA_Used_Good_KH_R0_FP2>2.42</tns:Auto_GRA_Used_Good_KH_R0_FP2>"+
						"<tns:Auto_GRA_Used_Good_KH_R1_FP0>2.43</tns:Auto_GRA_Used_Good_KH_R1_FP0>"+
						"<tns:Auto_GRA_Used_Good_KH_R1_FP1>2.44</tns:Auto_GRA_Used_Good_KH_R1_FP1>"+
						"<tns:Auto_GRA_Used_Good_KH_R1_FP2>2.45</tns:Auto_GRA_Used_Good_KH_R1_FP2>"+
						"<tns:Auto_GRA_Used_Good_KH_R2_FP0>2.46</tns:Auto_GRA_Used_Good_KH_R2_FP0>"+
						"<tns:Auto_GRA_Used_Good_KH_R2_FP1>2.47</tns:Auto_GRA_Used_Good_KH_R2_FP1>"+
						"<tns:Auto_GRA_Used_Good_KH_R2_FP2>2.48</tns:Auto_GRA_Used_Good_KH_R2_FP2>"+
						"<tns:Auto_GRA1_Used_Good_KH_R0_FP0>2.49</tns:Auto_GRA1_Used_Good_KH_R0_FP0>"+
						"<tns:Auto_GRA1_Used_Good_KH_R0_FP1>2.5</tns:Auto_GRA1_Used_Good_KH_R0_FP1>"+
						"<tns:Auto_GRA1_Used_Good_KH_R0_FP2>2.51</tns:Auto_GRA1_Used_Good_KH_R0_FP2>"+
						"<tns:Auto_GRA1_Used_Good_KH_R1_FP0>2.52</tns:Auto_GRA1_Used_Good_KH_R1_FP0>"+
						"<tns:Auto_GRA1_Used_Good_KH_R1_FP1>2.53</tns:Auto_GRA1_Used_Good_KH_R1_FP1>"+
						"<tns:Auto_GRA1_Used_Good_KH_R1_FP2>2.54</tns:Auto_GRA1_Used_Good_KH_R1_FP2>"+
						"<tns:Auto_GRA1_Used_Good_KH_R2_FP0>2.55</tns:Auto_GRA1_Used_Good_KH_R2_FP0>"+
						"<tns:Auto_GRA1_Used_Good_KH_R2_FP1>2.56</tns:Auto_GRA1_Used_Good_KH_R2_FP1>"+
						"<tns:Auto_GRA1_Used_Good_KH_R2_FP2>2.57</tns:Auto_GRA1_Used_Good_KH_R2_FP2>"+
						"<tns:Auto_GRB_Used_Good_KH_R0_FP0>2.58</tns:Auto_GRB_Used_Good_KH_R0_FP0>"+
						"<tns:Auto_GRB_Used_Good_KH_R0_FP1>2.59</tns:Auto_GRB_Used_Good_KH_R0_FP1>"+
						"<tns:Auto_GRB_Used_Good_KH_R0_FP2>2.6</tns:Auto_GRB_Used_Good_KH_R0_FP2>"+
						"<tns:Auto_GRB_Used_Good_KH_R1_FP0>2.61</tns:Auto_GRB_Used_Good_KH_R1_FP0>"+
						"<tns:Auto_GRB_Used_Good_KH_R1_FP1>2.62</tns:Auto_GRB_Used_Good_KH_R1_FP1>"+
						"<tns:Auto_GRB_Used_Good_KH_R1_FP2>2.63</tns:Auto_GRB_Used_Good_KH_R1_FP2>"+
						"<tns:Auto_GRB_Used_Good_KH_R2_FP0>2.64</tns:Auto_GRB_Used_Good_KH_R2_FP0>"+
						"<tns:Auto_GRB_Used_Good_KH_R2_FP1>2.65</tns:Auto_GRB_Used_Good_KH_R2_FP1>"+
						"<tns:Auto_GRB_Used_Good_KH_R2_FP2>2.66</tns:Auto_GRB_Used_Good_KH_R2_FP2>"+
						"<tns:Auto_GRC_Used_Good_KH_R0_FP0>2.76</tns:Auto_GRC_Used_Good_KH_R0_FP0>"+
						"<tns:Auto_GRC_Used_Good_KH_R0_FP1>2.77</tns:Auto_GRC_Used_Good_KH_R0_FP1>"+
						"<tns:Auto_GRC_Used_Good_KH_R0_FP2>2.78</tns:Auto_GRC_Used_Good_KH_R0_FP2>"+
						"<tns:Auto_GRC_Used_Good_KH_R1_FP0>2.79</tns:Auto_GRC_Used_Good_KH_R1_FP0>"+
						"<tns:Auto_GRC_Used_Good_KH_R1_FP1>2.8</tns:Auto_GRC_Used_Good_KH_R1_FP1>"+
						"<tns:Auto_GRC_Used_Good_KH_R1_FP2>2.81</tns:Auto_GRC_Used_Good_KH_R1_FP2>"+
						"<tns:Auto_GRC_Used_Good_KH_R2_FP0>2.82</tns:Auto_GRC_Used_Good_KH_R2_FP0>"+
						"<tns:Auto_GRC_Used_Good_KH_R2_FP1>2.83</tns:Auto_GRC_Used_Good_KH_R2_FP1>"+
						"<tns:Auto_GRC_Used_Good_KH_R2_FP2>2.84</tns:Auto_GRC_Used_Good_KH_R2_FP2>"+
						"<tns:Auto_GRC1_Used_Good_KH_R0_FP0>2.67</tns:Auto_GRC1_Used_Good_KH_R0_FP0>"+
						"<tns:Auto_GRC1_Used_Good_KH_R0_FP1>2.68</tns:Auto_GRC1_Used_Good_KH_R0_FP1>"+
						"<tns:Auto_GRC1_Used_Good_KH_R0_FP2>2.69</tns:Auto_GRC1_Used_Good_KH_R0_FP2>"+
						"<tns:Auto_GRC1_Used_Good_KH_R1_FP0>2.7</tns:Auto_GRC1_Used_Good_KH_R1_FP0>"+
						"<tns:Auto_GRC1_Used_Good_KH_R1_FP1>2.71</tns:Auto_GRC1_Used_Good_KH_R1_FP1>"+
						"<tns:Auto_GRC1_Used_Good_KH_R1_FP2>2.72</tns:Auto_GRC1_Used_Good_KH_R1_FP2>"+
						"<tns:Auto_GRC1_Used_Good_KH_R2_FP0>2.73</tns:Auto_GRC1_Used_Good_KH_R2_FP0>"+
						"<tns:Auto_GRC1_Used_Good_KH_R2_FP1>2.74</tns:Auto_GRC1_Used_Good_KH_R2_FP1>"+
						"<tns:Auto_GRC1_Used_Good_KH_R2_FP2>2.75</tns:Auto_GRC1_Used_Good_KH_R2_FP2>"+
						"<tns:Auto_GRD_Used_Good_KH_R0_FP0>2.85</tns:Auto_GRD_Used_Good_KH_R0_FP0>"+
						"<tns:Auto_GRD_Used_Good_KH_R0_FP1>2.86</tns:Auto_GRD_Used_Good_KH_R0_FP1>"+
						"<tns:Auto_GRD_Used_Good_KH_R0_FP2>2.87</tns:Auto_GRD_Used_Good_KH_R0_FP2>"+
						"<tns:Auto_GRD_Used_Good_KH_R1_FP0>2.88</tns:Auto_GRD_Used_Good_KH_R1_FP0>"+
						"<tns:Auto_GRD_Used_Good_KH_R1_FP1>2.89</tns:Auto_GRD_Used_Good_KH_R1_FP1>"+
						"<tns:Auto_GRD_Used_Good_KH_R1_FP2>2.9</tns:Auto_GRD_Used_Good_KH_R1_FP2>"+
						"<tns:Auto_GRD_Used_Good_KH_R2_FP0>2.91</tns:Auto_GRD_Used_Good_KH_R2_FP0>"+
						"<tns:Auto_GRD_Used_Good_KH_R2_FP1>2.92</tns:Auto_GRD_Used_Good_KH_R2_FP1>"+
						"<tns:Auto_GRD_Used_Good_KH_R2_FP2>2.93</tns:Auto_GRD_Used_Good_KH_R2_FP2>"+
						"<tns:Auto_GRE_Used_Good_KH_R0_FP0>2.94</tns:Auto_GRE_Used_Good_KH_R0_FP0>"+
						"<tns:Auto_GRE_Used_Good_KH_R0_FP1>2.95</tns:Auto_GRE_Used_Good_KH_R0_FP1>"+
						"<tns:Auto_GRE_Used_Good_KH_R0_FP2>2.96</tns:Auto_GRE_Used_Good_KH_R0_FP2>"+
						"<tns:Auto_GRE_Used_Good_KH_R1_FP0>2.97</tns:Auto_GRE_Used_Good_KH_R1_FP0>"+
						"<tns:Auto_GRE_Used_Good_KH_R1_FP1>2.98</tns:Auto_GRE_Used_Good_KH_R1_FP1>"+
						"<tns:Auto_GRE_Used_Good_KH_R1_FP2>2.99</tns:Auto_GRE_Used_Good_KH_R1_FP2>"+
						"<tns:Auto_GRE_Used_Good_KH_R2_FP0>3.1</tns:Auto_GRE_Used_Good_KH_R2_FP0>"+
						"<tns:Auto_GRE_Used_Good_KH_R2_FP1>3.11</tns:Auto_GRE_Used_Good_KH_R2_FP1>"+
						"<tns:Auto_GRE_Used_Good_KH_R2_FP2>3.12</tns:Auto_GRE_Used_Good_KH_R2_FP2>"+
					"</tns:SEGMENT_TARIFF_21>"+
					"<tns:SEGMENT_TARIFF_22>"+
						"<tns:MIN_FIRST_PAYMENT>15.0</tns:MIN_FIRST_PAYMENT>"+
						"<tns:RANGE_FRIRST_PAYMENT_1>30</tns:RANGE_FRIRST_PAYMENT_1>"+
						"<tns:RANGE_FIRST_PAYMENT_2>50</tns:RANGE_FIRST_PAYMENT_2>"+
					"</tns:SEGMENT_TARIFF_22>"+
				"</tns:PARAMS_TARIFF>"+
			"</tns:AUTO>"+
		"</tns:productInfoMessageRetail>");
		
		
	}
	
	public String getXml() {
		
		return this.xml;
	}
	
	public ArrayList<String> getdata() {
		
		return this.data;
	}

}
